package endpoints

func GetAuthToken() string {
	return "eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJlbWFpbCI6InNpZW1hbmtvQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhdXRoX3RpbWUiOjE3NDQxODgzNTQsInVzZXJfaWQiOiJqb1pEU3BEMGtLVm9MQkRjQmR2aGJOR0tNREZ6IiwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJzaWVtYW5rb0BnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9LCJpYXQiOjE3NDQxODgzNTQsImV4cCI6MTc0NDE5MTk1NCwiYXVkIjoic2hpbmstZ2ltaW5nbyIsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9zaGluay1naW1pbmdvIiwic3ViIjoiam9aRFNwRDBrS1ZvTEJEY0JkdmhiTkdLTURGeiJ9."
}
